/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CertifyRouteImport } from './routes/certify'
import { Route as FilieraRouteImport } from './routes/filiera'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManualeRouteImport } from './routes/manuale'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as ProtocolRouteImport } from './routes/protocol'
import { Route as ReportRouteImport } from './routes/report'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as DishDishIdRouteImport } from './routes/dish.$dishId'
import { Route as MenuRestaurantIdRouteImport } from './routes/menu.$restaurantId'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CertifyRoute = CertifyRouteImport.update({
  id: '/certify',
  path: '/certify',
  getParentRoute: () => rootRouteImport,
} as any)
const FilieraRoute = FilieraRouteImport.update({
  id: '/filiera',
  path: '/filiera',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualeRoute = ManualeRouteImport.update({
  id: '/manuale',
  path: '/manuale',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolRoute = ProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const DishDishIdRoute = DishDishIdRouteImport.update({
  id: '/dish/$dishId',
  path: '/dish/$dishId',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRestaurantIdRoute = MenuRestaurantIdRouteImport.update({
  id: '/$restaurantId',
  path: '/$restaurantId',
  getParentRoute: () => MenuRoute,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/certify': typeof CertifyRoute
  '/filiera': typeof FilieraRoute
  '/kiosk': typeof KioskRoute
  '/login': typeof LoginRoute
  '/manuale': typeof ManualeRoute
  '/menu': typeof MenuRouteWithChildren
  '/protocol': typeof ProtocolRoute
  '/report': typeof ReportRoute
  '/wallet': typeof WalletRoute
  '/dish/$dishId': typeof DishDishIdRoute
  '/menu/$restaurantId': typeof MenuRestaurantIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/certify': typeof CertifyRoute
  '/filiera': typeof FilieraRoute
  '/kiosk': typeof KioskRoute
  '/login': typeof LoginRoute
  '/manuale': typeof ManualeRoute
  '/menu': typeof MenuRouteWithChildren
  '/protocol': typeof ProtocolRoute
  '/report': typeof ReportRoute
  '/wallet': typeof WalletRoute
  '/dish/$dishId': typeof DishDishIdRoute
  '/menu/$restaurantId': typeof MenuRestaurantIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/certify': typeof CertifyRoute
  '/filiera': typeof FilieraRoute
  '/kiosk': typeof KioskRoute
  '/login': typeof LoginRoute
  '/manuale': typeof ManualeRoute
  '/menu': typeof MenuRouteWithChildren
  '/protocol': typeof ProtocolRoute
  '/report': typeof ReportRoute
  '/wallet': typeof WalletRoute
  '/dish/$dishId': typeof DishDishIdRoute
  '/menu/$restaurantId': typeof MenuRestaurantIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/certify'
    | '/filiera'
    | '/kiosk'
    | '/login'
    | '/manuale'
    | '/menu'
    | '/protocol'
    | '/report'
    | '/wallet'
    | '/dish/$dishId'
    | '/menu/$restaurantId'
    | '/product/$productId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/certify'
    | '/filiera'
    | '/kiosk'
    | '/login'
    | '/manuale'
    | '/menu'
    | '/protocol'
    | '/report'
    | '/wallet'
    | '/dish/$dishId'
    | '/menu/$restaurantId'
    | '/product/$productId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/certify'
    | '/filiera'
    | '/kiosk'
    | '/login'
    | '/manuale'
    | '/menu'
    | '/protocol'
    | '/report'
    | '/wallet'
    | '/dish/$dishId'
    | '/menu/$restaurantId'
    | '/product/$productId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  CertifyRoute: typeof CertifyRoute
  FilieraRoute: typeof FilieraRoute
  KioskRoute: typeof KioskRoute
  LoginRoute: typeof LoginRoute
  ManualeRoute: typeof ManualeRoute
  MenuRoute: typeof MenuRouteWithChildren
  ProtocolRoute: typeof ProtocolRoute
  ReportRoute: typeof ReportRoute
  WalletRoute: typeof WalletRoute
  DishDishIdRoute: typeof DishDishIdRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certify': {
      id: '/certify'
      path: '/certify'
      fullPath: '/certify'
      preLoaderRoute: typeof CertifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filiera': {
      id: '/filiera'
      path: '/filiera'
      fullPath: '/filiera'
      preLoaderRoute: typeof FilieraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manuale': {
      id: '/manuale'
      path: '/manuale'
      fullPath: '/manuale'
      preLoaderRoute: typeof ManualeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocol': {
      id: '/protocol'
      path: '/protocol'
      fullPath: '/protocol'
      preLoaderRoute: typeof ProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dish/$dishId': {
      id: '/dish/$dishId'
      path: '/dish/$dishId'
      fullPath: '/dish/$dishId'
      preLoaderRoute: typeof DishDishIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/$restaurantId': {
      id: '/menu/$restaurantId'
      path: '/$restaurantId'
      fullPath: '/menu/$restaurantId'
      preLoaderRoute: typeof MenuRestaurantIdRouteImport
      parentRoute: typeof MenuRoute
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MenuRouteChildren {
  MenuRestaurantIdRoute: typeof MenuRestaurantIdRoute
}

const MenuRouteChildren: MenuRouteChildren = {
  MenuRestaurantIdRoute: MenuRestaurantIdRoute,
}

const MenuRouteWithChildren = MenuRoute._addFileChildren(MenuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  CertifyRoute: CertifyRoute,
  FilieraRoute: FilieraRoute,
  KioskRoute: KioskRoute,
  LoginRoute: LoginRoute,
  ManualeRoute: ManualeRoute,
  MenuRoute: MenuRouteWithChildren,
  ProtocolRoute: ProtocolRoute,
  ReportRoute: ReportRoute,
  WalletRoute: WalletRoute,
  DishDishIdRoute: DishDishIdRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
